CHANGELOG.md, src/lib.rs, src/predicate/boxed.rs, src/predicate/mod.rs
Add `BoxPredicate` type that wraps a `Predicate` trait object to make it easier to store and work with predicates through a program by wrapping them as a heap-allocated trait object. Also implements `Debug` and `Display` wrappers as a convenience.
=> Add BoxPredicate type

src/lib.rs, src/predicate/function.rs, src/predicate/mod.rs
This adds a wrapper for functions of the form `Fn(&T) -> bool`, basically the same format as the `eval` function of `Predicate`. I think this provides a way more accessible option for evaluating the member fields of a struct than #2:
```
use predicates::predicate::{self, Predicate};
struct Example {
string: String,
number: i32,
}
let string_check = predicate::function(|x: &Example| x.string == "hello");
let number_check = predicate::function(|x: &Example| x.number == 42);
let predicate_fn = string_check.and(number_check);
let good_example = Example { string: "hello".into(), number: 42 };
assert_eq!(true, predicate_fn.eval(&good_example));
let bad_example = Example { string: "goodbye".into(), number: 0 };
assert_eq!(false, predicate_fn.eval(&bad_example));
```
This will probably also be …
=> Add FnPredicate type

.travis.yml, Cargo.toml, src/lib.rs, src/predicate/float/close.rs, src/predicate/float/mod.rs, src/predicate/mod.rs, src/predicate/path/existence.rs, src/predicate/path/ft.rs, src/predicate/path/mod.rs, src/predicate/str/difference.rs, src/predicate/str/mod.rs, src/predicate/str/regex.rs
- All external crates are optional
- Specialized functions are in a child module with a name for the type.
- Names would be verbose anyways
- This provides the user the opportunity to shorten it if they desire.
Particular notes
- Edit-distance is limited in use until #7 is implemented.  Its still nice to have now to help ensure #7 supports everything it needs
- I'm a little mixed on the regex API.  I'm starting to think its sufficient as is but we should probably document it to clarify how to work around the constrained by straight forward API.
=> Add specialized predicates

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, src/boolean.rs, src/boxed.rs, src/constant.rs, src/function.rs, src/lib.rs, src/ord.rs, src/set.rs
=> Documentation and Licensing

src/boolean.rs, src/boxed.rs, src/constant.rs, src/core.rs, src/float/close.rs, src/function.rs, src/lib.rs, src/ord.rs, src/path/existence.rs, src/path/ft.rs, src/set.rs, src/str/difference.rs, src/str/regex.rs
The hope is that generics will also make implementing support for #20
easier.  If nothing else, they'll give more control to users to implement things how they want.
So when to use each according to [The
Book](https://doc.rust-lang.org/book/second-edition/ch19-03-advanced-traits.html#associated-types-versus-generics):
Generics
- Used when type is going to be function input
- Can have multiple implementations of trait
Associated types
- Used when type is going to be a function output, like iterator
- Avoids need to annotate type
- Can only have one implementation of trait
BREAKING CHANGE: The `Predicate` trait's API has changed.
=> fix(API): Switch from Associated Types to Generics

src/boolean.rs, src/boxed.rs, src/core.rs, src/prelude.rs, src/str/adapters.rs, src/str/mod.rs
Existing "extra" functionality is now in extension traits.  This is a step to help pull `Predicate` in a separate crate and to set the pattern / standard for other helpers, like the ones added here.
=> Focus on extension traits

src/boolean.rs, src/boxed.rs, src/constant.rs, src/core.rs, src/float/close.rs, src/function.rs, src/iter.rs, src/lib.rs, src/name.rs, src/ord.rs, src/path/existence.rs, src/path/ft.rs, src/prelude.rs, src/str/adapters.rs, src/str/basics.rs, src/str/difference.rs, src/str/regex.rs
=> Implement `Display` support in lead up to #7

src/path/fc.rs, src/path/fs.rs
The reuse here is of little value but removing it gives a lot more
freedom in refactorung ... or disabling parts of the crate during major
refactors.
=> refactor: Reduce reuse

src/iter.rs, src/ord.rs
`eq("str")` wouldn't produce a `Predicate<str>` but instead a
`Predicate<&str>`, requiring the user to pass in a `&&str`.
=> feat: Fix eq for str

src/boolean.rs, src/constant.rs, src/float/close.rs, src/function.rs, src/iter.rs, src/name.rs, src/ord.rs, src/path/existence.rs, src/path/fc.rs, src/path/fs.rs, src/path/ft.rs, src/str/adapters.rs, src/str/basics.rs, src/str/difference.rs, src/str/regex.rs
We now consistently apply `Clone`, `Copy`, `PartialEq`, and `Eq`. It
looks like the derive macros are smart enough to conditionalize the
trait implementations for us.
=> feat: Expand trait coverage

src/function.rs
The implicit `T: Sized` bound on `FnPredicate` meant that function
predicates could not be used with slices or `str`. Removing that bound
by adding `T: ?Sized` to all the declarations makes this work.
I ran into this while trying to use a function predicate with assert_cmd's
[`Assert::stdout`](https://docs.rs/assert_cmd/0.6.0/assert_cmd/assert/struct.Assert.html#method.stdout)
method, which expects a `Predicate<[u8]>`. Without this patch it's not
possible to construct a `FnPredicate` that satisfies that.
=> Use T: ?Sized everywhere for FnPredicate so slices and str work

Cargo.toml, src/lib.rs, src/str/adapters.rs, src/str/mod.rs, src/str/normalize.rs
=> Normalize newlines

Cargo.toml, examples/case_tree.rs, src/boolean.rs, src/boxed.rs, src/constant.rs, src/core.rs, src/float/close.rs, src/function.rs, src/iter.rs, src/lib.rs, src/name.rs, src/ord.rs, src/path/existence.rs, src/path/fc.rs, src/path/fs.rs, src/path/ft.rs, src/reflection.rs, src/str/adapters.rs, src/str/basics.rs, src/str/difference.rs, src/str/normalize.rs, src/str/regex.rs, src/tree.rs
Output of `case_tree` example:
```
var is 5
((! var != 5) && var >= 5)
├── (! var != 5)
|   └── var != 5
└── var >= 5
```
An extension trait is added to make a `Display`able struct that will print out the above tree.
- This is built off of `find_case` which will find the `Case` that prove whether the `Predicate` succeeds or fails.
- To reduce overhead, `Case` only owns by-`Product`s of the `Predicate` evaluation, `parameters` are made available as references on the `PredicateReflection` trait
- This had the benefit of simplifying the `Case` API because `Parameter` and `Product` have different ownership requirements.
- `PredicateReflection` is also use to homogenize the predicate tree
- Because of predicate adapters, you could have a tree that includes `Predicate<[u8]>`, `Predicate<str>`, …
=> A way to display *why* a predicate failed

CHANGELOG.md, src/constant.rs
There is no reason that BooleanPredicate needs to be parameterized.
Removing its generic parameter allows it to always be Send and Sync
regardless of what type it's matching.
=> impl Send and Sync for BooleanPredicate

CHANGELOG.md, src/constant.rs
=> impl Predicate<T> for PredicateBoolean even if T: ?Sized

CHANGELOG.md, src/name.rs
The `NamePredicate` is quite handy for improving the readability of
failed assertions (in my case, when using the `mockall` crate). This PR
adds the specified name to the output of `find_case`, which `NamePredicate`
previously forwarded transparently to the child predicate.
=> Include NamePredicate in find_case results

CHANGELOG.md, Cargo.toml, src/lib.rs, src/prelude.rs, src/str/difference.rs, src/str/mod.rs
In the tree view, we already show the original and the current value, we
shouldnt show an entire Diff that is only parseable by color.
In changing this, we removed the more cosmetic atom selector.  We also
removed the edit distance, since there isn't a known case for it.  Let
us know if you needed this!
Fixes #94
Fixes #105
=> fix(diff): Remove duplicated output

crates/tree/src/lib.rs
Please see https://github.com/assert-rs/assert_cmd/pull/130 for the rationale behind this PR.
Separately, the `repository` entries in `predicates-core` and `predicates-tree`'s `Cargo.toml` files appear to be off. I could add those corrections to this PR, or submit them separately.
=> feat: Refine `CaseTreeInner` bounds

CHANGELOG.md, src/boolean.rs, src/function.rs, src/name.rs
Fix #108.
This fixes some predicates not being `Send` or `Sync` when `T` is not `Send` or `Sync`.
=> Implement `Send` and `Sync` for predicates with `PhantomData`

src/iter.rs, src/ord.rs, src/path/existence.rs, src/path/fc.rs, src/str/basics.rs, src/str/regex.rs
With some predicates, we show the user value (diff) but others do not.
This makes it more consistent.  We aim to show the user value in leaf
predicates and in major adapters.
- Some leaf predicates can't show a value (function)
- Some defer to a file on disk, so we leave it at that, in case the file
is too big or ugly to shoe
- Simple adapters, like `trim` don't show.  So far, the only worthwhile
one is `eq_file`.
By leaving things to the leaves, we are able to show the value after its
gone through transforms, like UTF-8, or loading a file path.
Fixes #116
=> fix: Report user value 

src/lib.rs
Thought we didn't document this but apparently I missed it though the
link was broken.
Fixes #120
=> docs: Fix `not`s link

src/iter.rs, src/ord.rs
It is very useful to be able to dynamically construct an object and have that object owned by the predicate, yet evaluate against an unowned type related to the owned one. An obvious example is a String being owned by the predicate but being compared against &strs.
Therefore, implement Predicate for Eq/OrdPredicate that store an object that implements Borrow for the predicate type, replacing existing impls of Predicate<T> for Eq/OrdPredicate<T> and Eq/OrdPredicate<&T>. This is backwards compatible as there are blanket implementations of Borrow<T> for T and Borrow<T> for &T.
Note that Borrow imposes more requirements than are actually required and AsRef would be sufficient. However, AsRef doesn't have a blanket implementation for T and thus the existing impl of Predicate<T> for …
=> feat: Allow predicates to own object and evaluate against borrowed types

.clippy.toml, .github/workflows/ci.yml, Cargo.toml, crates/core/Cargo.toml, crates/tree/Cargo.toml, src/color.rs, src/constant.rs, src/float/close.rs, src/function.rs, src/iter.rs, src/name.rs, src/ord.rs, src/path/existence.rs, src/path/fs.rs, src/path/ft.rs, src/str/basics.rs, src/str/difference.rs, src/str/regex.rs
This is in anticipation of callers using `anstyle_stream` to print this
which will "Do The Right Thing"
BREAKING CHANGE:
- `color-auto` is gone
- `Display`s won't automatically print ANSI color code when
appropriate but instead `format!("{}", case)` will never print color
and `format!("{:#}", case)` will always print color
=> feat!: Always print color when color is enabled 

.clippy.toml, .github/renovate.json5, .github/settings.yml, .github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/committed.yml, .github/workflows/pre-commit.yml, .github/workflows/rust-next.yml, .github/workflows/spelling.yml, Cargo.toml, src/boxed.rs, src/lib.rs, src/utils.rs
=> chore: Update from _rust/main template

CHANGELOG.md, src/boxed.rs
This looks like an oversight: the trait itself already had `Item: ?Sized` but the generic `impl` did not.
I noticed this while trying to chain together a variable number of `predicate::str::contains(...)` with `and()`. Calling `predicates::BoxPredicate::new()` explicitly works, but is much wordier than `.boxed()`, which fails:
```
173 | pub struct ContainsPredicate {
| ---------------------------- doesn't satisfy `_: PredicateBoxExt<str>`
|
= note: the following trait bounds were not satisfied:
`str: Sized`
which is required by `ContainsPredicate: predicates::PredicateBoxExt<str>`
`&ContainsPredicate: Predicate<_>`
which is required by `&ContainsPredicate: predicates::PredicateBoxExt<_>`
`&mut ContainsPredicate: Predicate<_>`
which is required by `&mut ContainsPredicate: …
```
=> feat: implement `PredicateBoxExt` for `?Sized` `Item`s

.github/workflows/ci.yml, .github/workflows/rust-next.yml, CHANGELOG.md, Cargo.toml, LICENSE-APACHE, README.md, crates/core/CHANGELOG.md, crates/core/Cargo.toml, crates/core/LICENSE-APACHE, crates/core/README.md, crates/core/release.toml, crates/core/src/lib.rs, crates/tree/CHANGELOG.md, crates/tree/Cargo.toml, crates/tree/LICENSE-APACHE, crates/tree/README.md, crates/tree/release.toml, crates/tree/src/lib.rs, deny.toml, release.toml, src/lib.rs
=> chore: Update from _rust template
